/*      Copyright 2002 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA 2.7
 *  Date       : 08-15-02
 */


package FinalProject;

import simView.*;

import java.awt.*;
import java.io.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;


public class Airstripsys extends ViewableDigraph{


public Airstripsys(){
    this("Airstripsys");
}

public Airstripsys(String nm){
    super(nm);
    AirstripSysConstruct();
}

public void AirstripSysConstruct(){

    this.addOutport("out");
    
    //domestic
    ViewableAtomic d_landing = new LandingGenr("LandingGenr",6);
    ViewableAtomic d_takeoff = new TakeOffGenr("TakeoffGenr",2);
    ViewableAtomic domestic = new DomesticAirstripController("DomesticAirstripController");
    add(d_landing);
     add(d_takeoff);
     add(domestic);
     addCoupling(d_landing,"LandingOut",domestic,"LandingIn");
     addCoupling(d_takeoff,"TakeOffOut",domestic,"TakeOffIn");
     
    //International
     ViewableAtomic i_landing = new InterLandingGenr("InterLandingGenr",4);
     ViewableAtomic i_takeoff = new InterTakeOffGenr("InterTakeoffGenr",3);
     ViewableAtomic inter = new InterAirstripController("InterAirstripController");

      add(i_landing);
      add(i_takeoff);
      add(inter);
      addCoupling(i_landing,"InterLandingOut",inter,"InterLandingIn");
      addCoupling(i_takeoff,"InterTakeOffOut",inter,"InterTakeOffIn");
      
   //final
      ViewableAtomic airstrip = new AirstripSystem("AirstripSystem");
   //  add(domestic);
    // add(inter);
     add(airstrip);
     addCoupling(domestic,"DomesticOut",airstrip,"DomesticIn");
     addCoupling(inter,"InterOut",airstrip,"InterIn");
     addCoupling(airstrip,"Requestout",this,"out");
     
}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1161, 434);
        if((ViewableComponent)withName("LandingGenr")!=null)
             ((ViewableComponent)withName("LandingGenr")).setPreferredLocation(new Point(-2, 12));
        if((ViewableComponent)withName("DomesticAirstripController")!=null)
             ((ViewableComponent)withName("DomesticAirstripController")).setPreferredLocation(new Point(257, 60));
        if((ViewableComponent)withName("InterTakeoffGenr")!=null)
             ((ViewableComponent)withName("InterTakeoffGenr")).setPreferredLocation(new Point(-2, 364));
        if((ViewableComponent)withName("AirstripSystem")!=null)
             ((ViewableComponent)withName("AirstripSystem")).setPreferredLocation(new Point(511, 179));
        if((ViewableComponent)withName("InterAirstripController")!=null)
             ((ViewableComponent)withName("InterAirstripController")).setPreferredLocation(new Point(325, 325));
        if((ViewableComponent)withName("InterLandingGenr")!=null)
             ((ViewableComponent)withName("InterLandingGenr")).setPreferredLocation(new Point(-10, 281));
        if((ViewableComponent)withName("TakeoffGenr")!=null)
             ((ViewableComponent)withName("TakeoffGenr")).setPreferredLocation(new Point(-5, 97));
    }
}
